### ISSUE TITLE
Support `AttributeUpdates`

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#104]
Ref: https://github.com/scylladb/scylla/issues/9542#issuecomment-955651638

**Comment by dimaqq** [comment]
Docs https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.AttributeUpdates.html

**Comment by ojii** [comment]
I decided not to support the "Legacy" parameters in aiodynamo and would prefer to keep it that way.

**Comment by dimaqq** [comment]
Ugh I guess I got confused by which was new and which was old.
