### ISSUE TITLE
How to update map element using a pattern?

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#108]
Described in https://dev.to/matthewvielkind/updating-values-in-dyanmodb-map-attributes-can

> ```py
> UpdateExpression="SET players.#player_id.score = :score_val",  
> ExpressionAttributeNames={"#player_id": player_id},  
> ```

I'm not sure what the API is in this case...
Would I need to overload `F`?

**Comment by ojii** [comment]
`F("players", player_id, "score").set(score_val)`

**Comment by dimaqq** [comment]
🤔 what if `player_id` evaluates to string, in case of nested mapping?

**Comment by ojii** [comment]
aiodynamo escapes all names, so that would translate to `SET #n1.#n2.#.n3 = :v1` with EAN `{"#n1": "players", "#n2": player_id, "#n3": "score"}`

**Comment by dimaqq** [comment]
Perfect!
Would be awesome to have a "recipes" section, but this is enough for me.
