### ISSUE TITLE
Get most recently added entry

### ISSUE THREAD

**Issue by torphix** [HENNGE/aiodynamo#148]
Hi, thanks for the awesome lib.

What is the best practice for getting the most recently added entry
My model has a attribute created_on that is the unix timestamp of when it was created I therefore just want to get the most recently added value ie: the one with the largest value

Thanks!

**Comment by ojii** [comment]
> My model has a attribute created_on that is the unix timestamp of when it was created I therefore just want to get the most recently added value ie: the one with the largest value

is `created_at` your sort/range key? if not, you might need to add a secondary index to your table. Please refer to AWS resources on this topic such as [this one explaining sort keys](https://aws.amazon.com/blogs/database/using-sort-keys-to-organize-data-in-amazon-dynamodb/) or [this one explaining indices](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html).

**Comment by torphix** [comment]
Thank you, I have set sort key to created_at. However I am a bit confused with the table.query() API.

Namely if I have to always pass a HashKey as an argument which requires also providing a unique ID won't the API always just fetch one unique item?

Sorry this is probably a really dumb question

**Comment by ojii** [comment]
> Namely if I have to always pass a HashKey as an argument which requires also providing a unique ID won't the API always just fetch one unique item?

Query only works if you use composite keys, where the combination of hash key and range key form a unique key, with many items sharing the same hash key. 

it would help to know your table/item schema and use case to help you.

**Comment by dimaqq** [comment]
Hash key doesn’t make a unique record.

hash key and range key together don’t make a unique record in a secondary index. Dynamo doesn’t have unique secondary indices by design.

hash key and range key do identify none or one record on the main index.

does this make sense?

**Comment by torphix** [comment]
Thanks for getting back to me ,
I worked it out using GSI's
