### ISSUE TITLE
Support Task Metadata Endpoint version 4

### ISSUE THREAD

**Issue by michaelaw320** [HENNGE/aiodynamo#39]
AWS just released Fargate platform 1.4.0 with new task metadata endpoint v4
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

**Comment by ojii** [comment]
task metadata is unrelated to aiodynamo. Credentials are fetched via [`AWS_CONTAINER_CREDENTIALS_(RELATIVE|FULL)_URI`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html). The Task Metadata Endpoint is for information about containers (like docker stats etc), not credentials.

**Comment by dimaqq** [comment]
I have a feeling that the credential refresh url is also present in task metadata.
Though if we get that from env, I guess it's fine?
