### ISSUE TITLE
Handle ClientConnectorError in connector

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#44]
Exception text: `ClientConnectorError: Cannot connect to host dynamodb.<snip>.amazonaws.com:443 ssl:default [None]`

Exception type: `aiohttp.client_exceptions.ClientConnectorError`

Stack:
```py
aiohttp/connector.py in _wrap_create_connection at line 943
aiohttp/connector.py in _create_direct_connection at line 980
aiohttp/connector.py in _create_direct_connection at line 1004
aiohttp/connector.py in _create_connection at line 858
aiohttp/connector.py in connect at line 523
aiohttp/client.py in _request at line 480
aiohttp/client.py in __aenter__ at line 1012
aiodynamo/http/aiohttp.py in post at line 31
aiodynamo/client.py in send_request at line 651
aiodynamo/client.py in get_item at line 454
aiodynamo/client.py in get_item at line 124
```

**Comment by dimaqq** [comment]
There are probably other exceptions of this kind that could be bundled together...

**Comment by ojii** [comment]
weird, `ClientConnectorError` is a subclass of `ClientError` which we catch.

**Comment by dimaqq** [comment]
The cause (?, I'm not sure which way exception stack grows):

`ConnectionAbortedError
SSL handshake is taking longer than 60.0 seconds: aborting the connection`

**Comment by dimaqq** [comment]
Weirdly `wrap_errors` is not shown in the backtrace...
I wonder if that's merely an artefact of how the decorator is applied, or something deeper?

**Comment by dimaqq** [comment]
> weird, `ClientConnectorError` is a subclass of `ClientError` which we catch.

Indeed it's odd, if I try it manually, I get:

```
ClientConnectorError: Cannot connect to host nowhere.com:443 ssl:default [Connect call failed ('89.31.143.1', 443)]

During handling of the above exception, another exception occurred:

RequestFailed                             Traceback (most recent call last)
<ipython-input-11-464539fe8630> in <module>
----> 1 await ai.get(url="https://nowhere.com",timeout=None)

~/aiodynamo/src/aiodynamo/http/aiohttp.py in wrapper(*args, **kwargs)
     18             return await coro(*args, **kwargs)
     19         except (ClientError, asyncio.TimeoutError):
---> 20             raise RequestFailed()
     21
     22     return wrapper

RequestFailed:
```

**Comment by dimaqq** [comment]
I think we're still running 20.4 and `wrap_errors` was added in 20.4.1 😅
