### ISSUE TITLE
Throttle loop should probably retry more errors:

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#47]
These 2 should be retried:

```py
    if status == 500:
        return InternalDynamoError()
    elif status == 503:
        raise ServiceUnavailable()
```

Possibly some other errors too.

**Comment by ojii** [comment]
[`ServiceUnavailable`](https://github.com/HENNGE/aiodynamo/blob/812db46260df759afa2478817067a1df2e2bfdfc/src/aiodynamo/client.py#L664) already is. I guess `InternalDynamoError` would also make sense.
