### ISSUE TITLE
Returns integers as float 😱

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#54]
As seen by `dynamodb-admin`:
```js
{
  [key omitted]
  "user_count": 4126,
  "foo_count": 0,
  "bar_count": 0,
  "mt": "1590462268"
}
```

Read by `aiodynamo`:
```js
{[key omitted], 'user_count': 4126.0, 'foo_count': 0.0, 'bar_count': 0.0, 'mt': '1590462268'}
```

**Comment by ojii** [comment]
You can specify the numeric type you want to use on a per-client basis: https://aiodynamo.readthedocs.io/en/latest/usage.html#client-instantiation

**Comment by dimaqq** [comment]
Indeed there's only one Numeric type in dynamo, but they say they accept data as strings and return it as strings. I don't know if that means they return what was set verbatim though.

I guess I was hoping for `float(v) if "." in v else int(v)` 🤔

**Comment by ojii** [comment]
> I guess I was hoping for `float(v) if "." in v else int(v)` 🤔

You can do that, `Client(..., numeric_type=lambda v: float(v) if "." in v else int(v), ...)`

boto libraries use `Decimal` which, while more precise/correct, are quite rare to use in Python (web) code in my experience and therefore rather unwieldy, hence aiodynamo defaulting to `float`.

**Comment by dimaqq** [comment]
I guess it's fine. I'm sure it's mentioned in the docs too...
