### ISSUE TITLE
query api not working with hashkeys with more than 1 character

### ISSUE THREAD

**Issue by uweje** [HENNGE/aiodynamo#57]
Hey
while experimenting with this library and one of my existing dynamodbs i encountered an issue when I use the query api.

```python
id = "1"
async for item in table.query(
    key_condition=HashKey("id", id) # this doesn't work
):
    print(item)
```
I got this exception
```
aiodynamo.errors.ValidationException: {'__type': 'com.amazon.coral.validate#ValidationException', 'message': 'KeyConditionExpressions cannot have conditions on nested attributes'}
```

I didn't use anything nested so I tried calling encode on the hashkey directly to find this
```
params = Parameters()
HashKey("id", "1").encode(params)  # output: '#n0.#n1 = :v0'
params.names  # output: {'#n0': 'i', '#n1': 'd'}
params.values  # output: {':v0': {'S': '1'}}
```
It seems to build a query "i.d = 1" instead of "id = 1"

I was able to query it correctly after wrapping the column name into a array but that goes against what the type of the name parameter for HashKey should be.

working example
```python
id = "1"
async for item in table.query(
    key_condition=HashKey(["id"], id)  # this works
):
    print(item)
```

**Comment by ojii** [comment]
@uweje thank you for reporting this issue, and sorry for this silly bug. A new version (20.10) has been released where this should be resolved.
