### ISSUE TITLE
What is "Candidate" ?

### ISSUE THREAD

**Issue by misogihagi** [HENNGE/aiodynamo#65]
when I tried 

```python3
from aiodynamo.client import Client
from aiodynamo.credentials import Credentials
from aiodynamo.http.aiohttp import AIOHTTP
from aiohttp import ClientSession
import asyncio

async def main():
    async with ClientSession() as session:
        client = Client(AIOHTTP(session), Credentials.auto(), "ap-northeast-1")
        table = client.table("table")
        await table.put_item(
          {
                'id':0,
                'data':"000"
            }
        )
        
asyncio.run(main())

```

and terminal showed below

> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodynamo\credentials.py", line 101, in get_key
>     key = await candidate.get_key(http)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodynamo\credentials.py", line 215, in get_key
>     await self._refresher
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodynamo\credentials.py", line 239, in _refresh
>     self._metadata = await self.fetch_metadata(http)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodynamo\credentials.py", line 338, in fetch_metadata
>     await self.fetch_with_retry(
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiodynamo\credentials.py", line 196, in fetch_with_retry
>     raise TooManyRetries()
> aiodynamo.credentials.TooManyRetries
> Candidate InstanceMetadataCredentials(timeout=1, max_attempts=1, base_url=URL('http://169.254.169.254'), disabled=False) failed

I think this problem because of my networking

> ping 169.254.169.254
> 
> Pinging 169.254.169.254 with 32 bytes of data:
> PING: transmit failed.
> PING: transmit failed.
> PING: transmit failed.
> PING: transmit failed.
> 
> Ping statistics for 169.254.169.254:
>     Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
> 

But according to boto3 available,  I think it doesn't need this process.

**Comment by dimaqq** [comment]
`aiodynamo` tries several ways (candidates) to get credentials to the server.
That particular ip address is a well-know value accessible either from docker container or aws instance (sorry I dunno which).
In short, `aiodynamo` couldn't find credentials for authentication.
(The error could be better of course)
`aiodynamo` does not use any `boto*` libraries.

I guess https://aiodynamo.readthedocs.io/en/latest/quickstart.html can be improved to show where to get credentials from 🤔

**Comment by ojii** [comment]
`Credentials.auto` tries to automatically find AWS credentials to access DynamoDB. The error you're seeing (I assume this is from a log, not an actual exception), is because no credentials could be found from the [Instance Metadata Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). 

If you know how to get the credentials, you can bypass `Credentials.auto` and use an explicit [credentials loader](https://aiodynamo.readthedocs.io/en/latest/usage.html#credentials). 

> But according to boto3 available, I think it doesn't need this process.

boto3 uses a similar (it actually tries even more things by default) process to find AWS credentials via [`botocore`](https://github.com/boto/botocore/blob/6e3ec4e8544ea32e130ac42b414a2819627c475b/botocore/credentials.py#L55). 

> That particular ip address is a well-known value accessible either from docker container or aws instance (I'm not sure which).

Just FYI, `169.254.169.254` is the Instance Metadata Service.

**Comment by misogihagi** [comment]
Thanks guys. after receiving your advices, I tried this

```python
import configparser
import os

home = os.path.expanduser("~")

config = configparser.ConfigParser()
config.read(os.path.join(home,".aws","credentials"))

from aiodynamo.client import Client
from aiodynamo.credentials import Credentials,StaticCredentials,Key
from aiodynamo.http.aiohttp import AIOHTTP
from aiohttp import ClientSession
import asyncio

async def main():
    async with ClientSession() as session:
        client = Client(AIOHTTP(session),StaticCredentials(Key(
          id= config['default']['aws_access_key_id'],
          secret= config['default']['aws_access_key_id']
        )), "ap-northeast-1")
        table = client.table("table")
        await table.put_item(
          {
                'id':10000000000,
                'data':"000"
            }
        )
        
asyncio.run(main())
```
this looks good to me, so I will be happy with credential file support:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

After all, this issue came from not my code but another reason, my proxy network.

> File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dynamodb.ap-northeast-1.amazonaws.com:443 ssl:default

**Comment by misogihagi** [comment]
Finally, I did it 
```python
import configparser
import os

home = os.path.expanduser("~")

config = configparser.ConfigParser()
config.read(os.path.join(home,".aws","credentials"))

from aiodynamo.client import Client
from aiodynamo.credentials import Credentials,StaticCredentials,Key
from aiodynamo.http.httpx import HTTPX
from httpx import AsyncClient
import asyncio

async def main():
    async with AsyncClient(proxies="http://proxy:3128") as session:
        client = Client(HTTPX(session),StaticCredentials(Key(
          id= config['default']['aws_access_key_id'],
          secret= config['default']['aws_secret_access_key']
        )), "ap-northeast-1")
        table = client.table("table")
        await table.put_item(
          {
                'id':10000000000,
                'data':"000"
            }
        )
        
asyncio.get_event_loop().run_until_complete(main())
```

(by the way, is this correct usage?)
