### ISSUE TITLE
Speed up deserialization

### ISSUE THREAD

**Issue by ojii** [HENNGE/aiodynamo#74]
When dealing with large items/large number of items, [`deserialize`](https://github.com/HENNGE/aiodynamo/blob/fdb05e944fa2335017201dc42e446b45c0ea57df/src/aiodynamo/utils.py#L25-L53) quickly becomes a bottleneck. The current version is already an optimized version over what botocore does (which is a major reason why aiodynamo is faster than botocore), but there is probably still room for improvement.

One option would be to include an (optional) cython version of the function.

**Comment by stupoid** [comment]
I took a crack at it here.

https://github.com/stupoid/aiodynamo/blob/458fd1316caff54409a186f346987289849530be/benchmarks/deserialize/new_deserialize.py

Basically just targeting low-hanging performance enhancements of avoiding that whole chain of `if`s by doing the work beforehand.

Benchmarks on my machine claims it's roughly ~65% faster?
```sh
$ pyperf compare_to aiodynamo.json new_deserialize.json
Mean +- std dev: [aiodynamo] 1.50 sec +- 0.08 sec -> [new_deserialize] 909 ms +- 94 ms: 1.65x faster
```

**Comment by dimaqq** [comment]
#78 is a good change;

However I don't think it "revolses" this issue entirely.
Other improvements are possible.
Next target, IMO, is to change this:

https://github.com/HENNGE/aiodynamo/blob/1bc49a7d6edb27772b3993294fb19e3f2b52644c/src/aiodynamo/utils.py#L24-L25

Calling a function in a Python loop is [most likely] a performance hit.
A few approaches that can be tried:

1. maybe unroll `deserialise` inside this loop `def d2p(): rv={}; for k, v in ...: rv[k]=<deser body here>(v); return rv`
2. maybe swap dict comprehension for `dict(map(<deser with 2 args>, data.items()))`
3. maybe some better idea?

**Comment by dimaqq** [comment]
> roughly ~65% faster

Ah, so confusing! I thought that 65% faster meant "takes 65% less time", which would be 2.86 times faster.
Instead, the claimed gain is 65% higher throughput, that is 1.65 times faster 🙈

**Comment by ojii** [comment]
> Calling a function in a Python loop is [most likely] a performance hit.

I've done a quick benchmark of inlining deserialize and `pyperf` says no significant change:

```python
def dy2py(data: DynamoItem, numeric_type: Callable[[str], Any]) -> Item:
    return {
        key: TAG_DESERIALIZE_MAPPING[tag](value, numeric_type)
        for key, (tag, value) in (
            (key, next(iter(dynamo_value.items())))
            for key, dynamo_value in data.items()
        )
    }
```

> * maybe swap dict comprehension for `dict(map(<deser with 2 args>, data.items()))`

this _should_ be slower than a dict comp.
