### ISSUE TITLE
allow newer httpx versions

### ISSUE THREAD

**Issue by uweje** [HENNGE/aiodynamo#80]
Hello

I noticed that aiodynamo still requires a old version of httpx from begining of 2020.
The current constrain `httpx = {version = "^0.11.1", optional = true}` limits the available versions to `>=0.11.1,<0.12` according to the [poetry documentation on version constrains](https://python-poetry.org/docs/dependency-specification/#version-constraints).

Would you mind trying it out with newer versions and relaxing the strict version constrain a bit?

Thank you

**Comment by ojii** [comment]
btw since it's optional, you can just not include that extra (assuming the httpx API didn't have breaking changes) and add it as a normal dependency to your project at a different version.

**Comment by dimaqq** [comment]
TIL that SemVer is tricky:
* `^0.2.0` accepts `0.2.x` and rejects `0.3.x`, but
* `^3.8.0` accepts `3.8.x through 3.10.x` and rejects `4.x.x`

We need to relax the `httpx` requirement. I'll test the newest and make the change.
